fcn:
  iAWE:
    epochs: 10
    batch_size: 128
    learning_rate: 0.001

  MotionSense:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001

resnet:
  iAWE:
    epochs: 10
    batch_size: 128
    learning_rate: 0.001

  MotionSense:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001

gru:
  iAWE:
    epochs: 10
    batch_size: 128
    learning_rate: 0.001

  MotionSense:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001

lstm:
  iAWE:
    epochs: 10
    batch_size: 128
    learning_rate: 0.001

  MotionSense:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001

gru:
  iAWE:
    epochs: 10
    batch_size: 128
    learning_rate: 0.001

  MotionSense:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001

transformer:
  iAWE:
    epochs: 10
    batch_size: 128
    learning_rate: 0.001

  MotionSense:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001